### ISSUE TITLE
複数のソースに対しても実行可能にする

### ISSUE THREAD

**Issue by shoppingjaws** [shoppingjaws/repo-file-sync#10]
```yaml
sources:
  - repo: shoppingjaws/kzdiff
    ref: main
    files:
    - README.md
  - repo: shoppingjaws/radio-station
    ref: main
    files:
    - .gitignore
```
この設定の場合、複数のリポジトリからもってくるようにしてください
