### ISSUE TITLE
テンプレート変数を注入可能にする

### ISSUE THREAD

**Issue by shoppingjaws** [shoppingjaws/repo-file-sync#12]
```yaml
sources:
  - repo: shoppingjaws/kzdiff
    ref: main
    files:
    - README.md
    vars:
      - key: HOGE
      - value: FUGA
 ```
README.mdのファイル内に記載されている`HOGE`という文字列をFUGAに置き換えるようにしてください
