### ISSUE TITLE
repo-file-syncのメイン実装

### ISSUE THREAD

**Issue by shoppingjaws** [shoppingjaws/repo-file-sync#7]
repo-file-sync.yaml
```yaml
sources:
  - repo: shoppingjaws/kzdiff
    ref: main
    files:
    - README.md
```

bunで上記のようなYAMLを読み込んで、ローカルにファイルを持ってくる処理を実装する。
上記のYAMLの場合、https://github.com/shoppingjaws/kzdiff/README.mdを持ってきます
